version: 0.0
os: linux

files:
  - source:  /
    destination: /var/www/html
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

# hooks:
#   AfterInstall:
#     - location: scripts/stop.sh
#       timeout: 60
#   ApplicationStart:
#     - location: scripts/start.sh
#       timeout: 60
#
